services:
  web:
    build: .
    command: python3 main.py config/config0.json
    ports:
      - "127.0.0.1:4000:4000"
    expose:
      - "4000"
    volumes:
      - .:/app
    links:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - 127.0.0.1:5432:5432
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=teodiomysql
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_video