version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: doc_db 
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=teodiomysql
      - POSTGRES_DB=doc_db
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local
