version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: doc_db 
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_HOST}:${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local
